### ISSUE TITLE
bug: returning to explore from my recipes doesn't maintain free search text

### ISSUE THREAD

**Issue by hagaishapira** [recipeify/Recipes#64]
Reproduce:

1. search for recipes with text and ingredients
2. go to my recipes
3. go to explore again
4. while the ingredients are still marked you don't see the free search text that was in the last query

We need to either clear the entire search session and just show explore without a search, or display the entire context.

**Comment by LeshemNoa** [comment]
Solved with https://github.com/recipeify/Recipes/pull/76
